### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by Spphire** [beapc18/AffordanceNet#3]
util/datasets/imdb.py 
line 17 from config_files.config_iit_masks import 
i didnt fint config_iit_masks.py in project

**Comment by FabianAsterLim** [comment]
did you find any solution to it?
Im running into the same issue.

**Comment by beapc18** [comment]
You can use one of these files: 
- https://github.com/beapc18/AffordanceNet/blob/main/config_files/config_iit_test.py
- https://github.com/beapc18/AffordanceNet/blob/main/config_files/config_iit_train.py

**Comment by ccjameslai** [comment]
Hi beapc18,
I have run "python3 affordancenet_predictor.py --config_file config_iit_test". But I received an error as following,
`imdb_names : voc_2012_test_iit
Loaded dataset `voc_2012_test` for training
Set proposal method: gt
Preparing training data...
Traceback (most recent call last):
  File "/home/james/Projects/AffordanceNet/affordancenet_predictor.py", line 65, in <module>
    imdb, roidb = data_utils.combined_roidb(cfg.IMDB_NAME, cfg.PROPOSAL_METHOD, cfg.USE_FLIPPED, mode="inference")
  File "/home/james/Projects/AffordanceNet/utils/data_utils.py", line 337, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "/home/james/Projects/AffordanceNet/utils/data_utils.py", line 337, in <listcomp>
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "/home/james/Projects/AffordanceNet/utils/data_utils.py", line 334, in get_roidb
    roidb = get_training_roidb(imdb, flipped, mode)
  File "/home/james/Projects/AffordanceNet/utils/data_utils.py", line 323, in get_training_roidb
    rdl_roidb.prepare_roidb(imdb)
  File "/home/james/Projects/AffordanceNet/utils/roi_data_layer/roidb.py", line 23, in prepare_roidb
    sizes = [PIL.Image.open(imdb.image_path_at(i)).size
  File "/home/james/Projects/AffordanceNet/utils/roi_data_layer/roidb.py", line 23, in <listcomp>
    sizes = [PIL.Image.open(imdb.image_path_at(i)).size
  File "/home/james/Projects/AffordanceNet/utils/datasets/pascal_voc.py", line 80, in image_path_at
    return self.image_path_from_index(self._image_index[i])
  File "/home/james/Projects/AffordanceNet/utils/datasets/pascal_voc.py", line 89, in image_path_from_index
    assert os.path.exists(image_path), \
AssertionError: Path does not exist: /home/james/Projects/AffordanceNet/data/VOCdevkit2012/VOC2012/JPEGImages/5`
How could I fix it?
Thank you very much.

**Comment by beapc18** [comment]
Hi ccjameslai,
Did you download the dataset and put it into the `/home/james/Projects/AffordanceNet/data` directory?

**Comment by ccjameslai** [comment]
Thank you, beapc18. I have done it. This is great helpful for me.

**Comment by wangcan2023** [comment]
Hi beapc18,I received an error as following
Traceback (most recent call last):
  File "/home/cc/cccc/AffordanceNet/affordancenet_predictor.py", line 64, in <module>
    imdb, roidb = data_utils.combined_roidb(cfg.IMDB_NAME, cfg.PROPOSAL_METHOD, cfg.USE_FLIPPED, mode="inference")
  File "/home/cc/cccc/AffordanceNet/utils/data_utils.py", line 337, in combined_roidb
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "/home/cc/cccc/AffordanceNet/utils/data_utils.py", line 337, in <listcomp>
    roidbs = [get_roidb(s) for s in imdb_names.split('+')]
  File "/home/cc/cccc/AffordanceNet/utils/data_utils.py", line 330, in get_roidb
    imdb = factory.get_imdb(imdb_name)
  File "/home/cc/cccc/AffordanceNet/utils/datasets/factory.py", line 38, in get_imdb
    return __sets[name]()
  File "/home/cc/cccc/AffordanceNet/utils/datasets/factory.py", line 20, in <lambda>
    __sets[name] = (lambda split=split, year=year, dataset=dataset: pascal_voc(split, year, dataset))
  File "/home/cc/cccc/AffordanceNet/utils/datasets/pascal_voc.py", line 51, in __init__
    self._image_index = self._load_image_set_index()
  File "/home/cc/cccc/AffordanceNet/utils/datasets/pascal_voc.py", line 101, in _load_image_set_index
    assert os.path.exists(image_set_file), \
AssertionError: Path does not exist: /home/cc/cccc/data/VOCdevkit2012/VOC2012/ImageSets/Main/test.txt

but my project is in folder /home/cc/cccc/AffordanceNet

and I want to ask for your help, the IIT dataset concludes four folders(affordance_labels,deep,object_labels,rgb), how could I fit the dataset with the need of your project base the path ( /home/cc/cccc/data/VOCdevkit2012/VOC2012/ImageSets/Main/test.txt)

**Comment by wangcan2023** [comment]
If it's possible, I'd really appreciate it if you could take a look at the question I posed, thank you very, very, very much!

2. when I created the files /home/cc/cccc/data/VOCdevkit2012/VOC2012/ImageSets/Main/ and copyed the test.txt from IIT dataset to it. I ran"python3 affordancenet_predictor.py --config_file config_iit_test". But I received an other error as following.
AssertionError: Path does not exist: /home/cc/cccc/data/VOCdevkit2012/VOC2012/JPEGImages/00_00000137.jpg.jpg

3. I tryed to copy the pictures of  rgb folder of the IIT dataset to JPEGImages/.
and I ran "python3 affordancenet_predictor.py --config_file config_iit_test". but I received an other error as following.
AssertionError: Path does not exist: /home/cc/cccc/data/VOCdevkit2012/VOC2012/JPEGImages/00_00000137.jpg.jpg

From the error message, I can see that there are two .jpg suffixes for the image.I checked the test.txt and the JPEGImages/ folder and I found there exists 00_00000137.jpg

4.I tried to modify the code to remove the extra image suffixes. and I ran "python3 affordancenet_predictor.py --config_file config_iit_test". but I received an other error as following.
FileNotFoundError: [Errno 2] No such file or directory: '/home/cc/cccc/AffordanceNet/data/VOCdevkit2012/VOC2012/Annotations/00_00000137.xml'

The IIT dataset does not have an .xml extension, how can I modify it to make the IIT dataset consistent with the requirements of your project?

If it's possible, I'd really appreciate it if you could take a look at the question I posed, thank you very, very, very much!

**Comment by beapc18** [comment]
The xml files are in the downloaded dataset, you have to follow the instructions in https://github.com/nqanh/affordance-net#training. It looks like the expected filename is different from the ones in the folder, you will have to look why. I only tested the code with the versions specified in the readme https://github.com/beapc18/AffordanceNet#requirements
