### ISSUE TITLE
training errors, weight count mismatch

### ISSUE THREAD

**Issue by FabianAster** [beapc18/AffordanceNet#4]
Hi beapc18,
Im currently trying to retrain the model, but i run into the issue, that the new hdf5 file doesnt work.
For training I used the IIT-AFF dataset, and the affordancenet_trainer.py.
To speed up training I also changed the Epochs to 2 in the config file, and reduced the amount of pictures to 500.
After training finishes there following error is thrown, but since the weights get saved before the dataset creation, i guess i can ignore the error right?

```
Traceback (most recent call last):
  File "/home/fabian/github/AffordanceNet/affordancenet_trainer.py", line 136, in <module>
    frcnn_model.save_weights(cfg.WEIGHTS_FILE)
  File "/home/fabian/miniconda3/envs/tf/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/fabian/miniconda3/envs/tf/lib/python3.9/site-packages/h5py/_hl/group.py", line 183, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File "/home/fabian/miniconda3/envs/tf/lib/python3.9/site-packages/h5py/_hl/dataset.py", line 165, in make_new_dset
    dset_id = h5d.create(parent.id, name, tid, sid, dcpl=dcpl, dapl=dapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 135, in h5py.h5d.create
ValueError: Unable to create dataset (name already exists)
```

But when trying to use the newly trained weights, the following weight count missmatch appears.
To solve that error, its possible to just delete the top level weights.

```
Traceback (most recent call last):
  File "/home/fabian/github/AffordanceNet/affordancenet_predictor.py", line 92, in <module>
    status = frcnn_model.load_weights(cfg.WEIGHTS_FILE, by_name=True)
  File "/home/fabian/miniconda3/envs/tf/lib/python3.9/site-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/fabian/miniconda3/envs/tf/lib/python3.9/site-packages/keras/saving/hdf5_format.py", line 864, in load_weights_from_hdf5_group_by_name
    raise ValueError(
ValueError: Weight count mismatch for top-level weights of model. Model expects 0 top-level weight(s). Received 55 saved top-level weight(s)
```
Also Ive noticed, that the .hdf5 files from the pretrained downloaded file has a few differently named keys than if its trained newly. Can that cause any issues?
When deleting the top level weights, the predictor runs, but it fails to detect anything at all.

**Comment by FabianAster** [comment]
1.st error can be ignored, and the top level weights only have to be removed in order for it to work
