### ISSUE TITLE
No module named 'config_files.config_iit_masks'

### ISSUE THREAD

**Issue by ajitham123** [beapc18/AffordanceNet#6]
Hi,

I am trying to run affordancenet_predictor.py using just the CPU in Ubuntu20, and I am getting this error:

ajitham@ajith-Ubuntu:~/tiago_public_ws/src/affordance-net/AffordanceNet$ python3 affordancenet_predictor.py --config_file config_iit_test

2023-11-17 10:01:13.929494: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2023-11-17 10:01:13.929518: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "affordancenet_predictor.py", line 3, in <module>
    from utils import io_utils, data_utils, train_utils, bbox_utils, drawing_utils, eval_utils
  File "/home/ajitham/tiago_public_ws/src/affordance-net/AffordanceNet/utils/data_utils.py", line 8, in <module>
    from utils.datasets import factory, imdb
  File "/home/ajitham/tiago_public_ws/src/affordance-net/AffordanceNet/utils/datasets/factory.py", line 12, in <module>
    from utils.datasets.pascal_voc import pascal_voc
  File "/home/ajitham/tiago_public_ws/src/affordance-net/AffordanceNet/utils/datasets/pascal_voc.py", line 9, in <module>
    from utils.datasets.imdb import imdb
  File "/home/ajitham/tiago_public_ws/src/affordance-net/AffordanceNet/utils/datasets/imdb.py", line 17, in <module>
    from config_files.config_iit_masks import Config
ModuleNotFoundError: No module named 'config_files.config_iit_masks'

I can clearly see the config_files folder. But apparently the required package linking fails. Do you know how to fix this? Thanks a lot!

**Comment by beapc18** [comment]
Hi, the solution was posted in https://github.com/beapc18/AffordanceNet/issues/3#issuecomment-1484173580
You have to replace the line https://github.com/beapc18/AffordanceNet/blob/e1b1bf81c67b4382ec6d435204b53bce0158bac5/utils/datasets/imdb.py#L17 with the config file you are using, config_iit_test or config_iit_train
